# Nginx — site CinéBase (VM1 : serveur web Django)
# À placer dans : /etc/nginx/sites-available/cinebase
# Activation :
#   rm /etc/nginx/sites-enabled/default
#   ln -s /etc/nginx/sites-available/cinebase /etc/nginx/sites-enabled/
#   systemctl restart nginx
#
# Remplacer [IP_VM_DJANGO] par l'adresse IP de la VM1 (serveur web).

server {
    listen 80;
    server_name [IP_VM_DJANGO];

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /home/toto/SAE-203-Albert/banque_films/static/;
    }

    location /media/ {
        alias /home/toto/SAE-203-Albert/banque_films/media/;
    }
}
